### ISSUE TITLE
Using npm as package manager fails when attempting to run `npm prepare` after installing packages

### ISSUE THREAD

**Issue by sircfenner** [seaofvoices/generator-luau#15]
Looks like this should be `(npm) run prepare`?

https://github.com/seaofvoices/generator-luau/blob/70906ec668a3551f82d7772d4d779a9144876c71/src/app/index.js#L597

<hr>

Looks like there is also a divergence elsewhere in the generator between calling `yarn prepare` and `yarn run prepare`, for example:

https://github.com/seaofvoices/generator-luau/blob/70906ec668a3551f82d7772d4d779a9144876c71/src/app/templates/scripts/build-single-file.sh#L12

https://github.com/seaofvoices/generator-luau/blob/70906ec668a3551f82d7772d4d779a9144876c71/src/app/githubWorkflow.js#L42

**Comment by jeparlefrancais** [comment]
I noticed the scripts to build a roblox model or to bundle also has a hard-coded yarn command, I'll fix that too! Thanks again for trying this out 🙂
